# Generated by Django 3.0 on 2019-12-12 12:47

from django.db import migrations, models
import kills.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dragon',
            fields=[
                ('name', models.CharField(max_length=10, unique=True)),
                ('id', models.CharField(default=kills.models.get_unique_id, max_length=50, primary_key=True, serialize=False)),
                ('last_timestamp', models.DateTimeField(blank=True, null=True)),
                ('animals_killed', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maximum_kills', models.IntegerField(default=0)),
                ('maximum_hours', models.IntegerField(default=0)),
                ('minimum_of_all_kills', models.IntegerField(default=0)),
                ('maximum_of_all_hours', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('DELETED', 'DELETED'), ('ACTIVE', 'ACTIVE')], default='ACTIVE', max_length=10)),
            ],
        ),
    ]
