# Generated by Django 3.0 on 2019-12-13 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dragon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('animals_killed', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Dragon',
                'verbose_name_plural': 'Dragons',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maximum_kills', models.IntegerField(default=0)),
                ('maximum_hours', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('DELETED', 'DELETED'), ('ACTIVE', 'ACTIVE')], default='ACTIVE', max_length=10)),
            ],
            options={
                'verbose_name': 'Rule',
                'verbose_name_plural': 'Rules',
            },
        ),
        migrations.CreateModel(
            name='Kills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('animals_killed', models.IntegerField(default=0)),
                ('dragon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kills.Dragon')),
            ],
            options={
                'verbose_name': 'Kills',
                'verbose_name_plural': 'Kills',
            },
        ),
    ]
