# Generated by Django 3.0 on 2019-12-12 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kills', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rule',
            options={'verbose_name': 'Rule', 'verbose_name_plural': 'Rules'},
        ),
        migrations.RemoveField(
            model_name='rule',
            name='maximum_of_all_hours',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='minimum_of_all_kills',
        ),
        migrations.CreateModel(
            name='Kills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(blank=True, null=True)),
                ('animals_killed', models.IntegerField(default=0)),
                ('dragon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kills.Dragon')),
            ],
            options={
                'verbose_name': 'Kills',
                'verbose_name_plural': 'Kills',
            },
        ),
    ]
