# Generated by Django 3.0 on 2019-12-12 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kills', '0002_auto_20191213_0035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dragon',
            options={'verbose_name': 'Dragon', 'verbose_name_plural': 'Dragons'},
        ),
        migrations.RemoveField(
            model_name='dragon',
            name='last_timestamp',
        ),
    ]
