# Generated by Django 3.0 on 2019-12-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kills', '0003_auto_20191213_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kills',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
